// RootLayout.js
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { LoadingProvider } from "./LoadingContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <LoadingProvider>
      <html lang="en">
        <body className="w-[80%] mx-auto my-5">
          <Navbar />
          {children}
        </body>
      </html>
    </LoadingProvider>
  );
}
